// Code generated by entc, DO NOT EDIT.

package semester

const (
	// Label holds the string label denoting the semester type in the database.
	Label = "semester"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSemester holds the string denoting the semester field in the database.
	FieldSemester = "semester"

	// EdgeScholarshipRequest holds the string denoting the scholarshiprequest edge name in mutations.
	EdgeScholarshipRequest = "ScholarshipRequest"

	// Table holds the table name of the semester in the database.
	Table = "semesters"
	// ScholarshipRequestTable is the table the holds the ScholarshipRequest relation/edge.
	ScholarshipRequestTable = "scholarship_requests"
	// ScholarshipRequestInverseTable is the table name for the ScholarshipRequest entity.
	// It exists in this package in order to avoid circular dependency with the "scholarshiprequest" package.
	ScholarshipRequestInverseTable = "scholarship_requests"
	// ScholarshipRequestColumn is the table column denoting the ScholarshipRequest relation/edge.
	ScholarshipRequestColumn = "semester_scholarship_request"
)

// Columns holds all SQL columns for semester fields.
var Columns = []string{
	FieldID,
	FieldSemester,
}

var (
	// SemesterValidator is a validator for the "Semester" field. It is called by the builders before save.
	SemesterValidator func(string) error
)
