// Code generated by entc, DO NOT EDIT.

package semester

import (
	"github.com/chat2542/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Semester applies equality check predicate on the "Semester" field. It's identical to SemesterEQ.
func Semester(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSemester), v))
	})
}

// SemesterEQ applies the EQ predicate on the "Semester" field.
func SemesterEQ(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSemester), v))
	})
}

// SemesterNEQ applies the NEQ predicate on the "Semester" field.
func SemesterNEQ(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSemester), v))
	})
}

// SemesterIn applies the In predicate on the "Semester" field.
func SemesterIn(vs ...string) predicate.Semester {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Semester(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSemester), v...))
	})
}

// SemesterNotIn applies the NotIn predicate on the "Semester" field.
func SemesterNotIn(vs ...string) predicate.Semester {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Semester(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSemester), v...))
	})
}

// SemesterGT applies the GT predicate on the "Semester" field.
func SemesterGT(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSemester), v))
	})
}

// SemesterGTE applies the GTE predicate on the "Semester" field.
func SemesterGTE(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSemester), v))
	})
}

// SemesterLT applies the LT predicate on the "Semester" field.
func SemesterLT(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSemester), v))
	})
}

// SemesterLTE applies the LTE predicate on the "Semester" field.
func SemesterLTE(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSemester), v))
	})
}

// SemesterContains applies the Contains predicate on the "Semester" field.
func SemesterContains(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSemester), v))
	})
}

// SemesterHasPrefix applies the HasPrefix predicate on the "Semester" field.
func SemesterHasPrefix(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSemester), v))
	})
}

// SemesterHasSuffix applies the HasSuffix predicate on the "Semester" field.
func SemesterHasSuffix(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSemester), v))
	})
}

// SemesterEqualFold applies the EqualFold predicate on the "Semester" field.
func SemesterEqualFold(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSemester), v))
	})
}

// SemesterContainsFold applies the ContainsFold predicate on the "Semester" field.
func SemesterContainsFold(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSemester), v))
	})
}

// HasScholarshipRequest applies the HasEdge predicate on the "ScholarshipRequest" edge.
func HasScholarshipRequest() predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ScholarshipRequestTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ScholarshipRequestTable, ScholarshipRequestColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasScholarshipRequestWith applies the HasEdge predicate on the "ScholarshipRequest" edge with a given conditions (other predicates).
func HasScholarshipRequestWith(preds ...predicate.ScholarshipRequest) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ScholarshipRequestInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ScholarshipRequestTable, ScholarshipRequestColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Semester) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Semester) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Semester) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		p(s.Not())
	})
}
