// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"

	// EdgeScholarshipRequest holds the string denoting the scholarshiprequest edge name in mutations.
	EdgeScholarshipRequest = "ScholarshipRequest"

	// Table holds the table name of the user in the database.
	Table = "users"
	// ScholarshipRequestTable is the table the holds the ScholarshipRequest relation/edge.
	ScholarshipRequestTable = "scholarship_requests"
	// ScholarshipRequestInverseTable is the table name for the ScholarshipRequest entity.
	// It exists in this package in order to avoid circular dependency with the "scholarshiprequest" package.
	ScholarshipRequestInverseTable = "scholarship_requests"
	// ScholarshipRequestColumn is the table column denoting the ScholarshipRequest relation/edge.
	ScholarshipRequestColumn = "user_scholarship_request"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldEmail,
}

var (
	// EmailValidator is a validator for the "Email" field. It is called by the builders before save.
	EmailValidator func(string) error
)
