// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// ScholarshipRequest is the predicate function for scholarshiprequest builders.
type ScholarshipRequest func(*sql.Selector)

// Scholarshipinformation is the predicate function for scholarshipinformation builders.
type Scholarshipinformation func(*sql.Selector)

// Scholarshiptype is the predicate function for scholarshiptype builders.
type Scholarshiptype func(*sql.Selector)

// Semester is the predicate function for semester builders.
type Semester func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
