// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/chat2542/app/ent/predicate"
	"github.com/chat2542/app/ent/scholarshipinformation"
	"github.com/chat2542/app/ent/scholarshiprequest"
	"github.com/chat2542/app/ent/scholarshiptype"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// ScholarshiptypeUpdate is the builder for updating Scholarshiptype entities.
type ScholarshiptypeUpdate struct {
	config
	hooks      []Hook
	mutation   *ScholarshiptypeMutation
	predicates []predicate.Scholarshiptype
}

// Where adds a new predicate for the builder.
func (su *ScholarshiptypeUpdate) Where(ps ...predicate.Scholarshiptype) *ScholarshiptypeUpdate {
	su.predicates = append(su.predicates, ps...)
	return su
}

// SetTypeName sets the Type_name field.
func (su *ScholarshiptypeUpdate) SetTypeName(s string) *ScholarshiptypeUpdate {
	su.mutation.SetTypeName(s)
	return su
}

// AddScholarshipinformationIDs adds the Scholarshipinformation edge to Scholarshipinformation by ids.
func (su *ScholarshiptypeUpdate) AddScholarshipinformationIDs(ids ...int) *ScholarshiptypeUpdate {
	su.mutation.AddScholarshipinformationIDs(ids...)
	return su
}

// AddScholarshipinformation adds the Scholarshipinformation edges to Scholarshipinformation.
func (su *ScholarshiptypeUpdate) AddScholarshipinformation(s ...*Scholarshipinformation) *ScholarshiptypeUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddScholarshipinformationIDs(ids...)
}

// AddScholarshipRequestIDs adds the ScholarshipRequest edge to ScholarshipRequest by ids.
func (su *ScholarshiptypeUpdate) AddScholarshipRequestIDs(ids ...int) *ScholarshiptypeUpdate {
	su.mutation.AddScholarshipRequestIDs(ids...)
	return su
}

// AddScholarshipRequest adds the ScholarshipRequest edges to ScholarshipRequest.
func (su *ScholarshiptypeUpdate) AddScholarshipRequest(s ...*ScholarshipRequest) *ScholarshiptypeUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddScholarshipRequestIDs(ids...)
}

// Mutation returns the ScholarshiptypeMutation object of the builder.
func (su *ScholarshiptypeUpdate) Mutation() *ScholarshiptypeMutation {
	return su.mutation
}

// RemoveScholarshipinformationIDs removes the Scholarshipinformation edge to Scholarshipinformation by ids.
func (su *ScholarshiptypeUpdate) RemoveScholarshipinformationIDs(ids ...int) *ScholarshiptypeUpdate {
	su.mutation.RemoveScholarshipinformationIDs(ids...)
	return su
}

// RemoveScholarshipinformation removes Scholarshipinformation edges to Scholarshipinformation.
func (su *ScholarshiptypeUpdate) RemoveScholarshipinformation(s ...*Scholarshipinformation) *ScholarshiptypeUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveScholarshipinformationIDs(ids...)
}

// RemoveScholarshipRequestIDs removes the ScholarshipRequest edge to ScholarshipRequest by ids.
func (su *ScholarshiptypeUpdate) RemoveScholarshipRequestIDs(ids ...int) *ScholarshiptypeUpdate {
	su.mutation.RemoveScholarshipRequestIDs(ids...)
	return su
}

// RemoveScholarshipRequest removes ScholarshipRequest edges to ScholarshipRequest.
func (su *ScholarshiptypeUpdate) RemoveScholarshipRequest(s ...*ScholarshipRequest) *ScholarshiptypeUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveScholarshipRequestIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (su *ScholarshiptypeUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := su.mutation.TypeName(); ok {
		if err := scholarshiptype.TypeNameValidator(v); err != nil {
			return 0, &ValidationError{Name: "Type_name", err: fmt.Errorf("ent: validator failed for field \"Type_name\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ScholarshiptypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *ScholarshiptypeUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *ScholarshiptypeUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *ScholarshiptypeUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *ScholarshiptypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   scholarshiptype.Table,
			Columns: scholarshiptype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: scholarshiptype.FieldID,
			},
		},
	}
	if ps := su.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.TypeName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: scholarshiptype.FieldTypeName,
		})
	}
	if nodes := su.mutation.RemovedScholarshipinformationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scholarshiptype.ScholarshipinformationTable,
			Columns: []string{scholarshiptype.ScholarshipinformationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarshipinformation.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.ScholarshipinformationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scholarshiptype.ScholarshipinformationTable,
			Columns: []string{scholarshiptype.ScholarshipinformationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarshipinformation.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := su.mutation.RemovedScholarshipRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scholarshiptype.ScholarshipRequestTable,
			Columns: []string{scholarshiptype.ScholarshipRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarshiprequest.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.ScholarshipRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scholarshiptype.ScholarshipRequestTable,
			Columns: []string{scholarshiptype.ScholarshipRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarshiprequest.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scholarshiptype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ScholarshiptypeUpdateOne is the builder for updating a single Scholarshiptype entity.
type ScholarshiptypeUpdateOne struct {
	config
	hooks    []Hook
	mutation *ScholarshiptypeMutation
}

// SetTypeName sets the Type_name field.
func (suo *ScholarshiptypeUpdateOne) SetTypeName(s string) *ScholarshiptypeUpdateOne {
	suo.mutation.SetTypeName(s)
	return suo
}

// AddScholarshipinformationIDs adds the Scholarshipinformation edge to Scholarshipinformation by ids.
func (suo *ScholarshiptypeUpdateOne) AddScholarshipinformationIDs(ids ...int) *ScholarshiptypeUpdateOne {
	suo.mutation.AddScholarshipinformationIDs(ids...)
	return suo
}

// AddScholarshipinformation adds the Scholarshipinformation edges to Scholarshipinformation.
func (suo *ScholarshiptypeUpdateOne) AddScholarshipinformation(s ...*Scholarshipinformation) *ScholarshiptypeUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddScholarshipinformationIDs(ids...)
}

// AddScholarshipRequestIDs adds the ScholarshipRequest edge to ScholarshipRequest by ids.
func (suo *ScholarshiptypeUpdateOne) AddScholarshipRequestIDs(ids ...int) *ScholarshiptypeUpdateOne {
	suo.mutation.AddScholarshipRequestIDs(ids...)
	return suo
}

// AddScholarshipRequest adds the ScholarshipRequest edges to ScholarshipRequest.
func (suo *ScholarshiptypeUpdateOne) AddScholarshipRequest(s ...*ScholarshipRequest) *ScholarshiptypeUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddScholarshipRequestIDs(ids...)
}

// Mutation returns the ScholarshiptypeMutation object of the builder.
func (suo *ScholarshiptypeUpdateOne) Mutation() *ScholarshiptypeMutation {
	return suo.mutation
}

// RemoveScholarshipinformationIDs removes the Scholarshipinformation edge to Scholarshipinformation by ids.
func (suo *ScholarshiptypeUpdateOne) RemoveScholarshipinformationIDs(ids ...int) *ScholarshiptypeUpdateOne {
	suo.mutation.RemoveScholarshipinformationIDs(ids...)
	return suo
}

// RemoveScholarshipinformation removes Scholarshipinformation edges to Scholarshipinformation.
func (suo *ScholarshiptypeUpdateOne) RemoveScholarshipinformation(s ...*Scholarshipinformation) *ScholarshiptypeUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveScholarshipinformationIDs(ids...)
}

// RemoveScholarshipRequestIDs removes the ScholarshipRequest edge to ScholarshipRequest by ids.
func (suo *ScholarshiptypeUpdateOne) RemoveScholarshipRequestIDs(ids ...int) *ScholarshiptypeUpdateOne {
	suo.mutation.RemoveScholarshipRequestIDs(ids...)
	return suo
}

// RemoveScholarshipRequest removes ScholarshipRequest edges to ScholarshipRequest.
func (suo *ScholarshiptypeUpdateOne) RemoveScholarshipRequest(s ...*ScholarshipRequest) *ScholarshiptypeUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveScholarshipRequestIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (suo *ScholarshiptypeUpdateOne) Save(ctx context.Context) (*Scholarshiptype, error) {
	if v, ok := suo.mutation.TypeName(); ok {
		if err := scholarshiptype.TypeNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Type_name", err: fmt.Errorf("ent: validator failed for field \"Type_name\": %w", err)}
		}
	}

	var (
		err  error
		node *Scholarshiptype
	)
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ScholarshiptypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *ScholarshiptypeUpdateOne) SaveX(ctx context.Context) *Scholarshiptype {
	s, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return s
}

// Exec executes the query on the entity.
func (suo *ScholarshiptypeUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *ScholarshiptypeUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *ScholarshiptypeUpdateOne) sqlSave(ctx context.Context) (s *Scholarshiptype, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   scholarshiptype.Table,
			Columns: scholarshiptype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: scholarshiptype.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Scholarshiptype.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := suo.mutation.TypeName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: scholarshiptype.FieldTypeName,
		})
	}
	if nodes := suo.mutation.RemovedScholarshipinformationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scholarshiptype.ScholarshipinformationTable,
			Columns: []string{scholarshiptype.ScholarshipinformationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarshipinformation.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.ScholarshipinformationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scholarshiptype.ScholarshipinformationTable,
			Columns: []string{scholarshiptype.ScholarshipinformationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarshipinformation.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := suo.mutation.RemovedScholarshipRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scholarshiptype.ScholarshipRequestTable,
			Columns: []string{scholarshiptype.ScholarshipRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarshiprequest.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.ScholarshipRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scholarshiptype.ScholarshipRequestTable,
			Columns: []string{scholarshiptype.ScholarshipRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarshiprequest.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	s = &Scholarshiptype{config: suo.config}
	_spec.Assign = s.assignValues
	_spec.ScanValues = s.scanValues()
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scholarshiptype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return s, nil
}
