// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/chat2542/app/ent/predicate"
	"github.com/chat2542/app/ent/scholarshiprequest"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// ScholarshipRequestDelete is the builder for deleting a ScholarshipRequest entity.
type ScholarshipRequestDelete struct {
	config
	hooks      []Hook
	mutation   *ScholarshipRequestMutation
	predicates []predicate.ScholarshipRequest
}

// Where adds a new predicate to the delete builder.
func (srd *ScholarshipRequestDelete) Where(ps ...predicate.ScholarshipRequest) *ScholarshipRequestDelete {
	srd.predicates = append(srd.predicates, ps...)
	return srd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (srd *ScholarshipRequestDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(srd.hooks) == 0 {
		affected, err = srd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ScholarshipRequestMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			srd.mutation = mutation
			affected, err = srd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(srd.hooks) - 1; i >= 0; i-- {
			mut = srd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, srd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (srd *ScholarshipRequestDelete) ExecX(ctx context.Context) int {
	n, err := srd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (srd *ScholarshipRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: scholarshiprequest.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: scholarshiprequest.FieldID,
			},
		},
	}
	if ps := srd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, srd.driver, _spec)
}

// ScholarshipRequestDeleteOne is the builder for deleting a single ScholarshipRequest entity.
type ScholarshipRequestDeleteOne struct {
	srd *ScholarshipRequestDelete
}

// Exec executes the deletion query.
func (srdo *ScholarshipRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := srdo.srd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{scholarshiprequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (srdo *ScholarshipRequestDeleteOne) ExecX(ctx context.Context) {
	srdo.srd.ExecX(ctx)
}
