// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/chat2542/app/ent/scholarshiprequest"
	"github.com/chat2542/app/ent/semester"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// SemesterCreate is the builder for creating a Semester entity.
type SemesterCreate struct {
	config
	mutation *SemesterMutation
	hooks    []Hook
}

// SetSemester sets the Semester field.
func (sc *SemesterCreate) SetSemester(s string) *SemesterCreate {
	sc.mutation.SetSemester(s)
	return sc
}

// AddScholarshipRequestIDs adds the ScholarshipRequest edge to ScholarshipRequest by ids.
func (sc *SemesterCreate) AddScholarshipRequestIDs(ids ...int) *SemesterCreate {
	sc.mutation.AddScholarshipRequestIDs(ids...)
	return sc
}

// AddScholarshipRequest adds the ScholarshipRequest edges to ScholarshipRequest.
func (sc *SemesterCreate) AddScholarshipRequest(s ...*ScholarshipRequest) *SemesterCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddScholarshipRequestIDs(ids...)
}

// Mutation returns the SemesterMutation object of the builder.
func (sc *SemesterCreate) Mutation() *SemesterMutation {
	return sc.mutation
}

// Save creates the Semester in the database.
func (sc *SemesterCreate) Save(ctx context.Context) (*Semester, error) {
	if _, ok := sc.mutation.Semester(); !ok {
		return nil, &ValidationError{Name: "Semester", err: errors.New("ent: missing required field \"Semester\"")}
	}
	if v, ok := sc.mutation.Semester(); ok {
		if err := semester.SemesterValidator(v); err != nil {
			return nil, &ValidationError{Name: "Semester", err: fmt.Errorf("ent: validator failed for field \"Semester\": %w", err)}
		}
	}
	var (
		err  error
		node *Semester
	)
	if len(sc.hooks) == 0 {
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SemesterMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sc.mutation = mutation
			node, err = sc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SemesterCreate) SaveX(ctx context.Context) *Semester {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sc *SemesterCreate) sqlSave(ctx context.Context) (*Semester, error) {
	s, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	s.ID = int(id)
	return s, nil
}

func (sc *SemesterCreate) createSpec() (*Semester, *sqlgraph.CreateSpec) {
	var (
		s     = &Semester{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: semester.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: semester.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.Semester(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: semester.FieldSemester,
		})
		s.Semester = value
	}
	if nodes := sc.mutation.ScholarshipRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   semester.ScholarshipRequestTable,
			Columns: []string{semester.ScholarshipRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarshiprequest.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return s, _spec
}
