// Code generated by entc, DO NOT EDIT.

package scholarshipinformation

const (
	// Label holds the string label denoting the scholarshipinformation type in the database.
	Label = "scholarshipinformation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldScholarshipName holds the string denoting the scholarship_name field in the database.
	FieldScholarshipName = "scholarship_name"

	// EdgeScholarshiptype holds the string denoting the scholarshiptype edge name in mutations.
	EdgeScholarshiptype = "Scholarshiptype"
	// EdgeScholarshipRequest holds the string denoting the scholarshiprequest edge name in mutations.
	EdgeScholarshipRequest = "ScholarshipRequest"

	// Table holds the table name of the scholarshipinformation in the database.
	Table = "scholarshipinformations"
	// ScholarshiptypeTable is the table the holds the Scholarshiptype relation/edge.
	ScholarshiptypeTable = "scholarshipinformations"
	// ScholarshiptypeInverseTable is the table name for the Scholarshiptype entity.
	// It exists in this package in order to avoid circular dependency with the "scholarshiptype" package.
	ScholarshiptypeInverseTable = "scholarshiptypes"
	// ScholarshiptypeColumn is the table column denoting the Scholarshiptype relation/edge.
	ScholarshiptypeColumn = "scholarshiptype_scholarshipinformation"
	// ScholarshipRequestTable is the table the holds the ScholarshipRequest relation/edge.
	ScholarshipRequestTable = "scholarship_requests"
	// ScholarshipRequestInverseTable is the table name for the ScholarshipRequest entity.
	// It exists in this package in order to avoid circular dependency with the "scholarshiprequest" package.
	ScholarshipRequestInverseTable = "scholarship_requests"
	// ScholarshipRequestColumn is the table column denoting the ScholarshipRequest relation/edge.
	ScholarshipRequestColumn = "scholarshipinformation_scholarship_request"
)

// Columns holds all SQL columns for scholarshipinformation fields.
var Columns = []string{
	FieldID,
	FieldScholarshipName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Scholarshipinformation type.
var ForeignKeys = []string{
	"scholarshiptype_scholarshipinformation",
}

var (
	// ScholarshipNameValidator is a validator for the "Scholarship_name" field. It is called by the builders before save.
	ScholarshipNameValidator func(string) error
)
