// Code generated by entc, DO NOT EDIT.

package scholarshiprequest

const (
	// Label holds the string label denoting the scholarshiprequest type in the database.
	Label = "scholarship_request"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "User"
	// EdgeScholarshiptype holds the string denoting the scholarshiptype edge name in mutations.
	EdgeScholarshiptype = "Scholarshiptype"
	// EdgeScholarshipinformation holds the string denoting the scholarshipinformation edge name in mutations.
	EdgeScholarshipinformation = "Scholarshipinformation"
	// EdgeSemester holds the string denoting the semester edge name in mutations.
	EdgeSemester = "Semester"

	// Table holds the table name of the scholarshiprequest in the database.
	Table = "scholarship_requests"
	// UserTable is the table the holds the User relation/edge.
	UserTable = "scholarship_requests"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the User relation/edge.
	UserColumn = "user_scholarship_request"
	// ScholarshiptypeTable is the table the holds the Scholarshiptype relation/edge.
	ScholarshiptypeTable = "scholarship_requests"
	// ScholarshiptypeInverseTable is the table name for the Scholarshiptype entity.
	// It exists in this package in order to avoid circular dependency with the "scholarshiptype" package.
	ScholarshiptypeInverseTable = "scholarshiptypes"
	// ScholarshiptypeColumn is the table column denoting the Scholarshiptype relation/edge.
	ScholarshiptypeColumn = "scholarshiptype_scholarship_request"
	// ScholarshipinformationTable is the table the holds the Scholarshipinformation relation/edge.
	ScholarshipinformationTable = "scholarship_requests"
	// ScholarshipinformationInverseTable is the table name for the Scholarshipinformation entity.
	// It exists in this package in order to avoid circular dependency with the "scholarshipinformation" package.
	ScholarshipinformationInverseTable = "scholarshipinformations"
	// ScholarshipinformationColumn is the table column denoting the Scholarshipinformation relation/edge.
	ScholarshipinformationColumn = "scholarshipinformation_scholarship_request"
	// SemesterTable is the table the holds the Semester relation/edge.
	SemesterTable = "scholarship_requests"
	// SemesterInverseTable is the table name for the Semester entity.
	// It exists in this package in order to avoid circular dependency with the "semester" package.
	SemesterInverseTable = "semesters"
	// SemesterColumn is the table column denoting the Semester relation/edge.
	SemesterColumn = "semester_scholarship_request"
)

// Columns holds all SQL columns for scholarshiprequest fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the ScholarshipRequest type.
var ForeignKeys = []string{
	"scholarshipinformation_scholarship_request",
	"scholarshiptype_scholarship_request",
	"semester_scholarship_request",
	"user_scholarship_request",
}
