// Code generated by entc, DO NOT EDIT.

package scholarshiprequest

import (
	"github.com/chat2542/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// HasUser applies the HasEdge predicate on the "User" edge.
func HasUser() predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "User" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasScholarshiptype applies the HasEdge predicate on the "Scholarshiptype" edge.
func HasScholarshiptype() predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ScholarshiptypeTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ScholarshiptypeTable, ScholarshiptypeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasScholarshiptypeWith applies the HasEdge predicate on the "Scholarshiptype" edge with a given conditions (other predicates).
func HasScholarshiptypeWith(preds ...predicate.Scholarshiptype) predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ScholarshiptypeInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ScholarshiptypeTable, ScholarshiptypeColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasScholarshipinformation applies the HasEdge predicate on the "Scholarshipinformation" edge.
func HasScholarshipinformation() predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ScholarshipinformationTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ScholarshipinformationTable, ScholarshipinformationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasScholarshipinformationWith applies the HasEdge predicate on the "Scholarshipinformation" edge with a given conditions (other predicates).
func HasScholarshipinformationWith(preds ...predicate.Scholarshipinformation) predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ScholarshipinformationInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ScholarshipinformationTable, ScholarshipinformationColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSemester applies the HasEdge predicate on the "Semester" edge.
func HasSemester() predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SemesterTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SemesterTable, SemesterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSemesterWith applies the HasEdge predicate on the "Semester" edge with a given conditions (other predicates).
func HasSemesterWith(preds ...predicate.Semester) predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SemesterInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SemesterTable, SemesterColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.ScholarshipRequest) predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.ScholarshipRequest) predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ScholarshipRequest) predicate.ScholarshipRequest {
	return predicate.ScholarshipRequest(func(s *sql.Selector) {
		p(s.Not())
	})
}
