/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersScholarshiprequest
 */
export interface ControllersScholarshiprequest {
    /**
     * 
     * @type {number}
     * @memberof ControllersScholarshiprequest
     */
    scholarshipinformation?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersScholarshiprequest
     */
    scholarshiptype?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersScholarshiprequest
     */
    semester?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersScholarshiprequest
     */
    user?: number;
}

export function ControllersScholarshiprequestFromJSON(json: any): ControllersScholarshiprequest {
    return ControllersScholarshiprequestFromJSONTyped(json, false);
}

export function ControllersScholarshiprequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersScholarshiprequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scholarshipinformation': !exists(json, 'scholarshipinformation') ? undefined : json['scholarshipinformation'],
        'scholarshiptype': !exists(json, 'scholarshiptype') ? undefined : json['scholarshiptype'],
        'semester': !exists(json, 'semester') ? undefined : json['semester'],
        'user': !exists(json, 'user') ? undefined : json['user'],
    };
}

export function ControllersScholarshiprequestToJSON(value?: ControllersScholarshiprequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'scholarshipinformation': value.scholarshipinformation,
        'scholarshiptype': value.scholarshiptype,
        'semester': value.semester,
        'user': value.user,
    };
}


