/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntScholarshipRequestEdges,
    EntScholarshipRequestEdgesFromJSON,
    EntScholarshipRequestEdgesFromJSONTyped,
    EntScholarshipRequestEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntScholarshipRequest
 */
export interface EntScholarshipRequest {
    /**
     * 
     * @type {EntScholarshipRequestEdges}
     * @memberof EntScholarshipRequest
     */
    edges?: EntScholarshipRequestEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntScholarshipRequest
     */
    id?: number;
}

export function EntScholarshipRequestFromJSON(json: any): EntScholarshipRequest {
    return EntScholarshipRequestFromJSONTyped(json, false);
}

export function EntScholarshipRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntScholarshipRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntScholarshipRequestEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntScholarshipRequestToJSON(value?: EntScholarshipRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntScholarshipRequestEdgesToJSON(value.edges),
        'id': value.id,
    };
}


