/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntScholarshipRequest,
    EntScholarshipRequestFromJSON,
    EntScholarshipRequestFromJSONTyped,
    EntScholarshipRequestToJSON,
    EntScholarshiptype,
    EntScholarshiptypeFromJSON,
    EntScholarshiptypeFromJSONTyped,
    EntScholarshiptypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntScholarshipinformationEdges
 */
export interface EntScholarshipinformationEdges {
    /**
     * ScholarshipRequest holds the value of the ScholarshipRequest edge.
     * @type {Array<EntScholarshipRequest>}
     * @memberof EntScholarshipinformationEdges
     */
    scholarshipRequest?: Array<EntScholarshipRequest>;
    /**
     * 
     * @type {EntScholarshiptype}
     * @memberof EntScholarshipinformationEdges
     */
    scholarshiptype?: EntScholarshiptype;
}

export function EntScholarshipinformationEdgesFromJSON(json: any): EntScholarshipinformationEdges {
    return EntScholarshipinformationEdgesFromJSONTyped(json, false);
}

export function EntScholarshipinformationEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntScholarshipinformationEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scholarshipRequest': !exists(json, 'scholarshipRequest') ? undefined : ((json['scholarshipRequest'] as Array<any>).map(EntScholarshipRequestFromJSON)),
        'scholarshiptype': !exists(json, 'scholarshiptype') ? undefined : EntScholarshiptypeFromJSON(json['scholarshiptype']),
    };
}

export function EntScholarshipinformationEdgesToJSON(value?: EntScholarshipinformationEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'scholarshipRequest': value.scholarshipRequest === undefined ? undefined : ((value.scholarshipRequest as Array<any>).map(EntScholarshipRequestToJSON)),
        'scholarshiptype': EntScholarshiptypeToJSON(value.scholarshiptype),
    };
}


