/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntScholarshipRequest,
    EntScholarshipRequestFromJSON,
    EntScholarshipRequestFromJSONTyped,
    EntScholarshipRequestToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntUserEdges
 */
export interface EntUserEdges {
    /**
     * ScholarshipRequest holds the value of the ScholarshipRequest edge.
     * @type {Array<EntScholarshipRequest>}
     * @memberof EntUserEdges
     */
    scholarshipRequest?: Array<EntScholarshipRequest>;
}

export function EntUserEdgesFromJSON(json: any): EntUserEdges {
    return EntUserEdgesFromJSONTyped(json, false);
}

export function EntUserEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntUserEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scholarshipRequest': !exists(json, 'scholarshipRequest') ? undefined : ((json['scholarshipRequest'] as Array<any>).map(EntScholarshipRequestFromJSON)),
    };
}

export function EntUserEdgesToJSON(value?: EntUserEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'scholarshipRequest': value.scholarshipRequest === undefined ? undefined : ((value.scholarshipRequest as Array<any>).map(EntScholarshipRequestToJSON)),
    };
}


